### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by canbax** [gimyboya/prayers.ts#1]
### Clear and concise description of the problem

I'm also trying to create such a calculator. Maybe we can help each other. I was scraping from an official website. But later it blocked me. Check my project https://github.com/canbax/namaz-vakti-api if you are interested

### Suggested solution

I want to calculate close to https://namazvakitleri.diyanet.gov.tr/ that's my goal. Scraping failed. I plan to re-write http://praytimes.org/code/git/?a=viewblob&p=PrayTimes&h=ab1c60335ec59683f2097d1876172b1dd784e36d&hb=HEAD&f=v2/js/PrayTimes.js

best regards

### Validations

- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by khawarizmus** [comment]
Hi there.

The documentation isn't finished yet but you can already achieve what you want with this library. by using any calculator provided to you by this library and use [Turkey](https://github.com/whiterocktech/prayers.ts/blob/master/src/types/Methods.ts#L9) calculation method in it's intialization options. example:
```ts
const calculator = new UseCalculator({
  date: new Date(2022, 1, 1), // put a date you want here if you want real time use the realtime calculator
  latitude: 2.9213, // change this to your location
  longitude: 101.6559,
  method: Methods.TURKEY, // An approximation of the Diyanet method used in Turkey. This approximation is less accurate outside the region of Turkey.
  adjustments: { dhuhr: 3, asr: 3, isha: 2 },
})
```
if you have more question feel free to ask. Also this library uses [Adhan-js] under the hood so you can refer to that for all options and possibilities.

**Comment by canbax** [comment]
So you didn't calculate the times here. Is that right? Also I see that prayTimes.org code uses latitude, longitude and **elevation** as well. Do you have world cities database or CSV file containing this information? I just found https://github.com/bahar/WorldCityLocations and it is ancient :)

**Comment by khawarizmus** [comment]
@canbax What is it that you want to achieve exactly? calculation methods and adjustments can change from city to city and country to country and might depend on many factors [including weather](https://github.com/batoulapps/adhan-js/issues/120#issuecomment-1197096343). currently [we don't have a compiled information about all the calculation methods](https://github.com/batoulapps/adhan-js/issues/41) used by every country however you can replicate any calculation method with this library as we provide a way to create a custom method instead of using the [provided ones](https://github.com/whiterocktech/prayers.ts/blob/master/src/types/Methods.ts#L1).

**Comment by canbax** [comment]
I want to replicate Turkey's method.

**Comment by khawarizmus** [comment]
@canbax this library already provides you with that method as i pointed out in my earlier comment. if you want the specific calculation params you can find them [here](https://github.com/batoulapps/adhan-js/blob/master/src/CalculationMethod.ts#L88)

**Comment by canbax** [comment]
thanks a lot I will try it

**Comment by khawarizmus** [comment]
Assalam alykoum @canbax 

For your information this library has reached a stable state and we have issued the documentation. as for your specific request please check this page of the docs https://prayers-call.netlify.app/config/methods.html

**Comment by canbax** [comment]
it's been like 1 year but thanks for the late response anyway 😂 I already achieved what I need using https://github.com/batoulapps/adhan-js
